version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}aspbackend
    build:
      context: .
      dockerfile: ToDoTask/Dockerfile
  #client:
  #  build: 
  #    dockerfile: React-frontend/Dockerfile