version: '3.4'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ToDoTask/Dockerfile
    volumes:
      - ./ToDoTask:/app/build
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 475269
      POSTGRES_USER: admin
      POSTGRES_DB: Tododb
    restart: always
    ports:
      - '5432'
    volumes:
      - mypgsql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
     - '8080:8080'

      
volumes:
  mypgsql_data:
