version: '3.4'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Asp-backend/Dockerfile
    volumes:
      - ./Asp-backend:/app/build
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:
      - "7000:80"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 475269
      POSTGRES_USER: admin
      POSTGRES_DB: Tododb
    restart: always
    volumes:
      - mypgsql_data:/var/lib/postgresql/data
    ports:
      - '5432'

  adminer:
    image: adminer
    restart: always
    ports:
     - '8080:8080'

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=745269
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      
volumes:
  mypgsql_data:
