version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    depends_on:
      - db
  db:
    environment:
      POSTGRES_PASSWORD: 475269
      POSTGRES_USER: admin
      POSTGRES_DB: Tododb
    ports:
      - '5432'

  adminer:
    ports:
      - '8080:8080'
  #client:
  #  ports:      
  #    - '3000:3000'
  #  volumes:
  #    - ./app/client
  #    - ./app/client/node_modules