global using Microsoft.EntityFrameworkCore;
global using AspBackend.Services.Interface;
global using AspBackend.CustomExceptions;
global using AspBackend.Models.Entity;
global using AspBackend.Services;
global using ToDoTask.Models;
global using Models.Responce;
global using Models.Request;
global using AutoMapper;